import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import supabase from '../utils/supabase'

export const getStaticProps = async () => {
  const { data: posts, error } = await supabase.from('posts').select('*')

  if (error) {
    throw new Error(error)
  }
  return {
    props: {
      posts
    }
  }
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello Chat</h1>
      <pre>{JSON.stringify(posts, null, 2)}</pre>
    </div>
  )
}
